### ISSUE TITLE
The pipeline resources comes from master instead of PR

### ISSUE THREAD

**Issue by beltran-rubo** [vmware-samples/vmware-image-builder-examples#11]
The pipeline resource files for the pipeline actions (Goss, Cypress, JMeter) are getting them from the target branch e.g. 'master' instead from the PR modified files.

E.g. [PR](https://github.com/bitnami/charts/pull/8841) and execution graph: 7c19a0d9-4460-4d03-ad22-61d57251a423.

**Comment by mpermar** [comment]
This is now fixed.
